### PR TITLE
Replaced mutable default argument

### PR DESCRIPTION
**Pull request by mentix02**
Default arguments shouldn't be mutable - https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument

### CODE REVIEW

**Review by pabluk — COMMENTED** [review]
Good catch :+1: 

If you want, please add your name into the "Author and contributors" section into the README.rst file.

After merge it I'll release a new version for pypi.

Thanks for your contribution @mentix02

**Comment by mentix02** [comment]
Thank you for this repo 😄

**Review by pabluk — APPROVED** [review]
LGTM 👍

**Comment by pabluk** [comment]
@mentix02 thanks again for your work, I just released a new version including your fix https://pypi.org/project/libgravatar/0.2.5/

**Pull request merged**
